services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER:-pocketledger}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-pocketledger}
      POSTGRES_DB: ${DB_NAME:-pocketledger}
    ports:
      - "127.0.0.1:5433:5432" # host 127.0.0.1:5433 -> avoid exposing to network, avoid clashing with a local Postgres on 5432
    volumes:
      - pocketledger-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-pocketledger} -d ${DB_NAME:-pocketledger}"]
      interval: 5s
      timeout: 5s
      retries: 10

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686" # Jaeger UI: http://localhost:16686
      - "4317:4317" # OTLP gRPC receiver

  app:
    build:
      context: .
      target: runtime
    environment:
      DATABASE_URL: postgresql+psycopg://${DB_USER:-pocketledger}:${DB_PASSWORD:-pocketledger}@db:5432/${DB_NAME:-pocketledger}
      OTEL_EXPORTER_OTLP_ENDPOINT: jaeger:4317
      JWT_SECRET: ${JWT_SECRET:-dev-only-secret-change-me}
      ENVIRONMENT: development
    ports:
      - "8000:8000" # API + docs: http://localhost:8000/docs
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/srv

  app-test:
    build:
      context: .
      target: test
    environment:
      DATABASE_URL: postgresql+psycopg://${DB_USER:-pocketledger}:${DB_PASSWORD:-pocketledger}@db:5432/${DB_NAME:-pocketledger}_test
      OTEL_EXPORTER_OTLP_ENDPOINT: jaeger:4317
      JWT_SECRET: ${JWT_SECRET:-dev-only-secret-change-me}
      ENVIRONMENT: test
      TEST_DATABASE_URL: postgresql+psycopg://${DB_USER:-pocketledger}:${DB_PASSWORD:-pocketledger}@db:5432/${DB_NAME:-pocketledger}_test
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/srv

volumes:
  pocketledger-db-data:
